black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 254
  - 90
  min:
  - 0
  - 120
  - 0
green:
  max:
  - 255
  - 112
  - 165
  min:
  - 0
  - 1
  - 98
red:
  max:
  - 228
  - 255
  - 255
  min:
  - 0
  - 167
  - 135
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
